### ISSUE TITLE
Search button should be there

### ISSUE THREAD

**Issue by hrc7505** [blackdeve/React-Typescript-Maps#1]
A "Search Result" text is not button and should not have a click! 
There should be a search button to get locations. Go to get locations only if both zip code and radius are provided. You should have three columns for this.
- Column for zip code part
- Column for radius part 
- Column for search button. 

You should make it responsive too!

**Comment by blackdeve** [comment]
![search button](https://user-images.githubusercontent.com/36166782/45319298-caf17d80-b582-11e8-8a30-cf0575ecb7cb.png)

The design has no search button.
Where should the search button be?

**Comment by mintyfusion** [comment]
We will just make the Zip Code/Postal Code text box and Radius smaller and add "Search" button next to it.

**Comment by blackdeve** [comment]
Done
