### ISSUE TITLE
Border of empty column

### ISSUE THREAD

**Issue by hrc7505** [blackdeve/React-Typescript-Maps#2]
After getting the locations, if we have only one location then why we render other two columns? You are rendering the empty "listColumns" and because of this border showing on empty column(2nd column)!

![image](https://user-images.githubusercontent.com/17545364/45281322-1b21fe80-b4f5-11e8-9595-d35e34fc927e.png)

In addition, you should handle a case of no locations. You should show a message like "No locations available" if locations are not available.

**Comment by blackdeve** [comment]
Done

**Comment by blackdeve** [comment]
Done
