### ISSUE TITLE
List column should be a component and need improvements in SearchResultItem component

### ISSUE THREAD

**Issue by hrc7505** [blackdeve/React-Typescript-Maps#3]
I think you are rewriting multiple lines of code needlessly. 
![image](https://user-images.githubusercontent.com/17545364/45281866-c5e6ec80-b4f6-11e8-8804-58156b3e935e.png)

You should make a separate component for `<ListColumn/>` and just pass in the array of locations! And should put a condition inside `<ListColumn/>` component for no locations. If array is empty or null then component should return `null`. 
One more thing to reduce the code you need to get improve is `<SearchResultItem/>` component. You are passing the props to this component one by one even when your array property names and names of the <SearchResultItem/> component props! I think it will be better to use spread(...) operator there. For example:
```
locations.map((location: ILocation, i: number) => (
  <SearchResultItem  key={i} {...location} />
)
```
And I suggest you to use stateless component instead of class if there is no logic available!

--------------------------------
One more thing about making the column structure. You used three loop to create 3 columns and this is not optimal solution and it will be hard(lots of changes) to make this responsive too. I think you should go with row structure having single loop to render location tiles and you can make it responsive with little css changes!

**Comment by blackdeve** [comment]
Done
