### ISSUE TITLE
Linting issues

### ISSUE THREAD

**Issue by hrc7505** [blackdeve/React-Typescript-Maps#4]
**1. Import should be in below groups and add space between groups:** 

1. third party imports(Like React/ReactDOM library imports and other third party imports)
2. Self created components import
3. css file imports

  For example:
```
import * as React from "react";
import * as ReactDOM from "react-dom";
import {GoogleMap, Marker, withGoogleMap, withScriptjs} from "react-google-maps";
			
import CustomGoogleMap from "CustomGoogleMap";
			
import './CustomGoogleMap.css';
```
			
**2. Imports should be sorted as below ordered-imports property value in tslint:**
```
 "ordered-imports": [
      true,
      {
        "import-sources-order": "case-insensitive",
        "module-source-path":"basename", 
        "named-imports-order": "case-insensitive",
        "grouped-imports": true
      }
    ],
```

**3. Use `" "`(double quotes) instead of `' '`(single quotes)**
**4. Type definitions should follow the below rule in tslint:**
```
"typedef": [
      true,
        "call-signature",
        "parameter", 
        "member-variable-declaration",
        "arrow-call-signature",
        "property-declaration",
        "variable-declaration",
        "arrow-parameter"
    ],
```
**5. Member ordering should be:**
```
"public-static-field",
"public-instance-field",
"public-constructor",
"private-static-field",
"private-instance-field",
"private-constructor",
"public-instance-method",
"protected-instance-method",
"private-instance-method"
```
**6. Use `let `instead of `var` if value is reassigned to a variable**
**7. Use `const `instead of `let`/`var `if value never reassigned to a variable**
**8. Not allow magic numbers except -1.
9. A every javascript statement should be end with semicolon
10.  Never use type `any`. Because of this typescript will become useless! Use proper typings.**
**11. All class member should be marked with `public`, `private `or `protected `according to the use of them.**
**12. Object keys should be sorted alphabetically.  
13. Parentheses are required around the parameters of an arrow function definition.
14. `for (... in ...)` statements must be filtered with an if statement
15, Remove trailing whitespace
16. Do not use non-arrow functions. [`App.tsx` - line number-> 68]
17. Use `===` instead of `==` during comparison [`App.tsx` - line number-> 69]
18. Add missing whitespace at required places(code formatting issues)
19. File should be end with new line
20. Should be a blank line before return.
21. An arrow function body can be simplified by omitting the curly braces and the keyword 'return'. [`CustomeGoogleMap.tsx` - line number-> 9]
22. A comment must start with space.
23. Do not imports with explicit side-effect. If you want to add then use file extension as below where css import will be ignored by tslint:(`firebase.ts` - line number-> 2)**
`"no-import-side-effect": [true, {"ignore-module": "(\\.css)$"}]`

I hope you have knowledge of tslint. It will make this easier for you. Otherwise you can get more about [TsLint](https://palantir.github.io/tslint/) here!

**Comment by blackdeve** [comment]
Fixed
