### ISSUE TITLE
Do not use THAT=this !

### ISSUE THREAD

**Issue by hrc7505** [blackdeve/React-Typescript-Maps#5]
We do not need to save instance of the class in `THAT `like variable to use it inside the functions. 
![image](https://user-images.githubusercontent.com/17545364/45291867-f0de3a00-b510-11e8-9579-25e6de04c17d.png)
Just use es6 standard _arrow function_ to make this easier! Use the instance(`this`) directly inside the arrow function!

**Comment by blackdeve** [comment]
Removed `THAT` and changed to arrow function
